### ISSUE TITLE
没搞懂这一波git操作和一个小问题

### ISSUE THREAD

**Issue by eiyooooo** [Lyric0620/ETSAuto#37]
没搞懂这一波git操作

另外
https://github.com/Yutong-gannis/ETSAuto/blob/cac7de77e1e1b7c3334a68477f346cd3cb05112c/script/main.py#L97-L99
被后面的
https://github.com/Yutong-gannis/ETSAuto/blob/cac7de77e1e1b7c3334a68477f346cd3cb05112c/script/main.py#L113-L134
给覆盖了吧

**Comment by Lyric0620** [comment]
@eiyooooo  主要是增加了几个线程，然后写了一个等红绿灯的，还没整理好，一直放主函数里的。后面多的检测已经删除了，我这边没开游戏跑了一下，应该没问题

**Comment by eiyooooo** [comment]
@Yutong-gannis 以后是按版本来开branch吗，main是不用了吗
还有我看代码里有个yolov6s_bdd_300但是release里只有yolov6s_bdd_60🤨

**Comment by Lyric0620** [comment]
@eiyooooo main不用了，现在默认branch在1.1。我准备修改感知部分，交通标志检测继续用yolov6，物体准备用单目3D做了。现在单目3D还在调参训练，到时候会一起更新。
