### ISSUE TITLE
第一遍用cuda10.2不成功，改用cuda11.7遇到了这样的问题

### ISSUE THREAD

**Issue by lihuang218** [Lyric0620/ETSAuto#40]
在构建 YOLOV6 的 TensorRT 文件时报错如下：

python ./tools/export.py -o ./engines/yolov6s_bdd_60.onnx -e ./engines/yolov6s_bdd_60.engine --end2end
Traceback (most recent call last):
  File "./tools/export.py", line 7, in <module>
    import tensorrt as trt
  File "E:\python\lib\site-packages\tensorrt\__init__.py", line 129, in <module>
    ctypes.CDLL(find_lib(lib))
  File "E:\python\lib\site-packages\tensorrt\__init__.py", line 93, in find_lib
    raise FileNotFoundError(
FileNotFoundError: Could not find: cublas64_10.dll. Is it on your PATH?
Note: Paths searched were:
['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\libnvvp', 'E:\\python\\Scripts\\', 'E:\\python\\', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'F:\\Program Files\\Polyspace\\R2021a\\runtime\\win64', 'F:\\Program Files\\Polyspace\\R2021a\\bin', 'F:\\Program Files\\Polyspace\\R2021a\\polyspace\\bin', 'F:\\git\\Git\\cmd', 'C:\\Program Files (x86)\\GnuWin32\\bin', 'C:\\Program Files\\CMake\\bin', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'F:\\epic\\Epic Games\\UE_4.24\\Engine\\Binaries\\Win64', 'F:\\7ZIP\\7-Zip', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.2.0\\', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\lib', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\include', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\libnvvp', 'E:\\tensorrt\\TensorRT-8.4.2.4.Windows10.x86_64.cuda-11.6.cudnn8.4\\TensorRT-8.4.2.4\\lib', 'E:\\cudnn\\cudnn-windows-x86_64-8.7.0.84_cuda11-archive\\bin', 'E:\\tensorrt\\TensorRT-8.4.2.4.Windows10.x86_64.cuda-11.6.cudnn8.4\\TensorRT-8.4.2.4\\bin', 'C:\\Users\\student\\AppData\\Local\\Microsoft\\WindowsApps', '', 'F:\\vscode\\Microsoft VS Code\\bin', 'F:\\banzip\\']
PS D:\ETSAuto\ETSAuto-1.1>

但是构建 CLRNet 的 TensorRT 文件没有报错

构建 环境感知 的 TensorRT 文件依旧报相同的错

PS D:\ETSAuto\ETSAuto-1.1> python ./tools/onnx2trt.py
Traceback (most recent call last):
  File "./tools/onnx2trt.py", line 2, in <module>
    import tensorrt as trt
  File "E:\python\lib\site-packages\tensorrt\__init__.py", line 129, in <module>
    ctypes.CDLL(find_lib(lib))
  File "E:\python\lib\site-packages\tensorrt\__init__.py", line 93, in find_lib
    raise FileNotFoundError(
FileNotFoundError: Could not find: cublas64_10.dll. Is it on your PATH?
Note: Paths searched were:
['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\libnvvp', 'E:\\python\\Scripts\\', 'E:\\python\\', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'F:\\Program Files\\Polyspace\\R2021a\\runtime\\win64', 'F:\\Program Files\\Polyspace\\R2021a\\bin', 'F:\\Program Files\\Polyspace\\R2021a\\polyspace\\bin', 'F:\\git\\Git\\cmd', 'C:\\Program Files (x86)\\GnuWin32\\bin', 'C:\\Program Files\\CMake\\bin', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'F:\\epic\\Epic Games\\UE_4.24\\Engine\\Binaries\\Win64', 'F:\\7ZIP\\7-Zip', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2022.2.0\\', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\lib', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\include', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\libnvvp', 'E:\\tensorrt\\TensorRT-8.4.2.4.Windows10.x86_64.cuda-11.6.cudnn8.4\\TensorRT-8.4.2.4\\lib', 'E:\\cudnn\\cudnn-windows-x86_64-8.7.0.84_cuda11-archive\\bin', 'E:\\tensorrt\\TensorRT-8.4.2.4.Windows10.x86_64.cuda-11.6.cudnn8.4\\TensorRT-8.4.2.4\\bin', 'C:\\Users\\student\\AppData\\Local\\Microsoft\\WindowsApps', '', 'F:\\vscode\\Microsoft VS Code\\bin', 'F:\\banzip\\']

**Comment by Lyric0620** [comment]
@lihuang218 `FileNotFoundError: Could not find: cublas64_10.dll. Is it on your PATH?` 找一下cuda安装目录下有没有`cublas64_10.dll`这个文件，或者有没有`cublas64_xx.dll`，如果有改成`cublas64_10.dll`试试。

**Comment by lihuang218** [comment]
有一个cublas64_11.dll，修改后依旧报错

PS D:\ETSAuto\ETSAuto-1.1> python ./tools/export.py -o ./engines/yolov6s_bdd_60.onnx -e ./engines/yolov6s_bdd_60.engine --end2end
Traceback (most recent call last):
  File "./tools/export.py", line 7, in <module>
    import tensorrt as trt
  File "E:\python\lib\site-packages\tensorrt\__init__.py", line 129, in <module>
    ctypes.CDLL(find_lib(lib))
  File "E:\python\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cublas64_10.dll' (or one of its dependencies). Try using the full path with constructor syntax.
PS D:\ETSAuto\ETSAuto-1.1>

**Comment by Lyric0620** [comment]
@lihuang218 `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin`在这个目录下吗

**Comment by lihuang218** [comment]
在我C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin在这个目录下。

将cuda10.2中的cublas64_10.dll复制到C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin中，可以成功构建 YOLOV6 的 TensorRT 文件。

但是在构建 环境感知 的 TensorRT 文件时报错如下：
[04/14/2023-20:25:03] [TRT] [V] --------------- Timing Runner: Conv_9 + Add_10 (CudnnConvolution)
[04/14/2023-20:25:03] [TRT] [V] CudnnConvolution has no valid tactics for this config, skipping
[04/14/2023-20:25:03] [TRT] [V] --------------- Timing Runner: Conv_9 + Add_10 (CublasConvolution)
[04/14/2023-20:25:03] [TRT] [V] CublasConvolution has no valid tactics for this config, skipping
[04/14/2023-20:25:03] [TRT] [V] --------------- Timing Runner: Conv_9 + Add_10 (CaskConvolution)
[04/14/2023-20:25:03] [TRT] [V] CaskConvolution has no valid tactics for this config, skipping
[04/14/2023-20:25:03] [TRT] [V] Deleting timing cache: 435 entries, served 806 hits since creation.
[04/14/2023-20:25:03] [TRT] [E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::3626] Error Code 10: Internal Error (Could not find any implementation for node Conv_9 + Add_10.)
Traceback (most recent call last):
  File "./tools/onnx2trt.py", line 55, in <module>
    build_engine(ONNX_SIM_MODEL_PATH, TENSORRT_ENGINE_PATH_PY)
  File "./tools/onnx2trt.py", line 49, in build_engine
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'

**Comment by Lyric0620** [comment]
@lihuang218 用trtexec转试试
