### ISSUE TITLE
构建 CLRNet 的 TensorRT 文件

### ISSUE THREAD

**Issue by SimonSin1106** [Lyric0620/ETSAuto#42]
輸入polygraphy surgeon sanitize 路徑\engines\llamas_dla34.onnx --fold-constants --output 路徑\engines\llamas_dla34_tmp.onnx trtexec --onnx=路徑\engines\llamas_dla34_tmp.onnx --saveEngine=路徑\engines\llamas_dla34.engine

顯示polygraphy : 無法辨識 'polygraphy' 詞彙是否為 Cmdlet、函數、指令檔或可執行程式的名稱。請檢查名稱拼字是否正確，如果包含路徑的
話，請確認路徑是否正確，然後再試一次。
位於 線路:1 字元:1
+ polygraphy surgeon sanitize F:\auto\ETSAuto-1.1\ETSAuto-1.1\engines\l ...
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (polygraphy:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
    請問哪裡沒設定好?

**Comment by Lyric0620** [comment]
@SimonSin1106 这是tensorrt自带的工具，请检查一下tensorrt是否安装好

**Comment by SimonSin1106** [comment]
> @SimonSin1106 这是tensorrt自带的工具，请检查一下tensorrt是否安装好

這個我都是去nvidia官網下載但是文件內沒有這個polygraphy,我另外去下載放下去解決了,現在我運行了軟件,運行時python.exe佔用了7x% CPU使用率再加上遊戲我的CPU長期維持在99%,我有甚麼要設定的嗎?
開啟自動駕駛發現軟件沒有進行車道線檢測,我看視頻你的軟件一直有綠色線但是我沒有,哪邊出錯誤了嗎?

**Comment by Lyric0620** [comment]
@SimonSin1106 不好意思，刚刚看了一下，这个是要用pip安装的`pip install polygraphy` 。CPU占用高可能是我使用了多线程的原因。
车道线算法用的是CLRNET，一些朋友表示推理时间太长了，所以在1.1版本被注释掉了。可放开下面代码85行，注释掉98行进行车道线检测。
https://github.com/Yutong-gannis/ETSAuto/blob/64f1aeda3b68dff6a55cfa3a001e9f523d0af2ea/script/main.py#L85-L98

**Comment by SimonSin1106** [comment]
@Yutong-gannis 沒有行車道線檢測也是小事,可是自動駕駛開啟了一直左撞右撞是甚麼問題呢

**Comment by Lyric0620** [comment]
@SimonSin1106 识别导航线的问题，下面的小地图要改成最大的，然后游戏窗口要调到合适位置

**Comment by SimonSin1106** [comment]
@Yutong-gannis 下面的小地图要改成最大的，然后游戏窗口要调到合适位置我都調好了,看軟件識別車輛不是在導航線正中間

**Comment by Lyric0620** [comment]
@SimonSin1106 需要对窗口进行一些小幅度移动，才能保证自车在正中间

**Comment by SimonSin1106** [comment]
@Yutong-gannis 這個不懂喔,是把遊戲窗口向左/右移動嗎?

> @SimonSin1106 需要对窗口进行一些小幅度移动，才能保证自车在正中间

**Comment by Lyric0620** [comment]
@SimonSin1106 是的

**Comment by SimonSin1106** [comment]
> @SimonSin1106 是的

@Yutong-gannis 可是我把窗口移動了亦看到軟件識別了車在2條白線中間,行車時會慢慢偏向,修正方向很慢,會到處撞

**Comment by SimonSin1106** [comment]
@Yutong-gannis 可是我把窗口移動了亦看到軟件識別了車在2條白線中間,行車時會慢慢偏向,修正方向很慢,會到處撞,要怎麼才能解決

**Comment by Lyric0620** [comment]
@SimonSin1106 可能是速度太快了。如果是这样的话，调整一下INFO类下面的速度梯度
##X-3Kea7JFOfJY16I##PAGE

**Comment by SimonSin1106** [comment]
> @SimonSin1106 可能是速度太快了。如果是这样的话，调整一下INFO类下面的速度梯度 ##X-3Kea7JFOfJY16I##PAGE

@Yutong-gannis 抱歉,能教一下在哪邊調整嗎?

**Comment by Lyric0620** [comment]
@SimonSin1106 稍等一会😂我用手机编辑的粘贴不了代码

**Comment by SimonSin1106** [comment]
> @SimonSin1106 稍等一会😂我用手机编辑的粘贴不了代码

@Yutong-gannis 還有就是軟件運行起來,畫面有時候會閃爍是我的電腦效能不夠嗎?

**Comment by Lyric0620** [comment]
@SimonSin1106 关于车速梯度的设置在这里。
https://github.com/Yutong-gannis/ETSAuto/blob/14cd24426d6505601eab0baee5364495fe62c68c/Control/drive.py#L52-L69

我这边还没有出现过闪烁的问题，可能是效能问题。

**Comment by SimonSin1106** [comment]
> @SimonSin1106 关于车速梯度的设置在这里。
> 
> https://github.com/Yutong-gannis/ETSAuto/blob/14cd24426d6505601eab0baee5364495fe62c68c/Control/drive.py#L52-L69
> 
> 我这边还没有出现过闪烁的问题，可能是效能问题。

@Yutong-gannis 我使用i7-8700K跟GTX1070Ti不夠嗎?

**Comment by Lyric0620** [comment]
@SimonSin1106  我是第九代的i5和GTX1650笔记本。应该是没问题的。

**Comment by SimonSin1106** [comment]
> @SimonSin1106 我是第九代的i5和GTX1650笔记本。应该是没问题的。

@Yutong-gannis 運行軟件cpu立馬使用率100%

**Comment by Lyric0620** [comment]
@SimonSin1106 我的也有这种现象，还不知道是哪里的问题。可能确实使用率比较大
