### ISSUE TITLE
导入错误ImportError: lap requires numpy

### ISSUE THREAD

**Issue by frozenbird07** [Lyric0620/ETSAuto#44]
按照所有配置好环境以后，运行main.py报错  ModuleNotFoundError: No module named 'lap'
接着尝试pip install lap ，但是一直安装失败，提示 ImportError: lap requires numpy, please "pip install numpy".
可是numpy早就装上了，pip list里也能看到，接着换了几个版本的numpy都不行，系统win11，cuda11,7，torch 1.13.1
百度也搜不到解决的方法

**Comment by Lyric0620** [comment]
@frozenbird07 `pip install git+git://github.com/gatagat/lap.git`这样下

**Comment by frozenbird07** [comment]
挂梯子代理错误，不挂梯子又443，最后我是直接克隆下来本地编译安装上的
