### ISSUE TITLE
构建TensorRT 文件时遇到的一个问题

### ISSUE THREAD

**Issue by stxxxd** [Lyric0620/ETSAuto#46]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/48894972/d80ab226-0f03-41fa-8e25-996a8faa4dee)
求助！
其他两个权重文件可以正常构建

**Comment by Lyric0620** [comment]
@stxxxd 貌似这个权重文件有问题 用这个仓库转https://github.com/xuanandsix/CLRNet-onnxruntime-and-tensorrt-demo

**Comment by stxxxd** [comment]
> @stxxxd 貌似这个权重文件有问题 用这个仓库转https://github.com/xuanandsix/CLRNet-onnxruntime-and-tensorrt-demo

好的 感谢 话说大佬这个点还没睡啊

**Comment by Lyric0620** [comment]
@stxxxd 准备毕业答辩嘞

**Comment by stxxxd** [comment]
> @stxxxd 准备毕业答辩嘞

祝大佬答辩顺利

**Comment by Lyric0620** [comment]
@stxxxd 放出的代码没用车道线检测
https://github.com/Yutong-gannis/ETSAuto/blob/14cd24426d6505601eab0baee5364495fe62c68c/script/main.py#L85-L98
如果要用的话，把85行放开，98行注释掉

**Comment by stxxxd** [comment]
> 

好的
