### ISSUE TITLE
识别不出来道路怎么办呢？

### ISSUE THREAD

**Issue by fyzzy1943** [Lyric0620/ETSAuto#52]
能识别出来车辆，但是识别不出来道路，一开始运行就一直往前跑，也不会拐弯。

**Comment by fyzzy1943** [comment]
屏幕的分辨率会有影响吗？

**Comment by Lyric0620** [comment]
@fyzzy1943 屏幕分辨率只能用1360x768
道路识别需要自己修改https://github.com/Yutong-gannis/ETSAuto/issues/46#issuecomment-1564701616

**Comment by fyzzy1943** [comment]
> @fyzzy1943 屏幕分辨率只能用1360x768 道路识别需要自己修改[#46 (comment)](https://github.com/Yutong-gannis/ETSAuto/issues/46#issuecomment-1564701616)

3Q，车道线出来了，但是识别好卡，感觉1秒才刷一次，车来回撞。我是1070的显卡，是显卡不够用嘛？

**Comment by Lyric0620** [comment]
@fyzzy1943 我用的GTX1650，响应时间大概为0.16s左右

**Comment by fyzzy1943** [comment]
> @fyzzy1943 我用的GTX1650，响应时间大概为0.16s左右

Orz 不知道咋搞啦

**Comment by Lyric0620** [comment]
@fyzzy1943 我使用了更小的网络，应该可以用了
