### ISSUE TITLE
关于bevmap比例问题

### ISSUE THREAD

**Issue by NNNNemo** [Lyric0620/ETSAuto#54]
bevmap的比例尺是多少呢？如下代码所定义，bevmap是一个600x800的numpy数组，但单位好像并不是m。
`    bevmap = np.ones((600, 800)) * 75
`
我打印出检测到的汽车，其宽为8，长为20，如果单位是m，显然与事实不符，0.2m似乎更合理些。 
<img width="337" alt="image" src="https://github.com/Yutong-gannis/ETSAuto/assets/57900805/20cc8122-bdd2-4358-ae1c-10c2f6965ef7">
所以，请问一下有具体的比例尺吗？

**Comment by Lyric0620** [comment]
@NNNNemo bevmap是从导航地图仿射变换后得到的，所以尺度比较模糊
