### ISSUE TITLE
關於迥旋重疊路線問題

### ISSUE THREAD

**Issue by see963852** [Lyric0620/ETSAuto#55]
導航地圖中有迥旋重疊路線,方向會導致錯誤應該怎樣解決?
例如下面圖像中,行駛到交叉線時候,車輛會轉左邊行駛,而不是直去

![未命名](https://github.com/Yutong-gannis/ETSAuto/assets/95551416/c965fcd4-ecf6-4428-9733-ed1936ad4767)

**Comment by Lyric0620** [comment]
@see963852 
这个问题将在后续版本中进行解决
