### ISSUE TITLE
關於ETSAuto 2.0dev 橫向移動問題

### ISSUE THREAD

**Issue by see963852** [Lyric0620/ETSAuto#56]
我用了1.0的项目转向基本上没有问题，但是用了2.0的项目，转向弯道转不了，我已经把游戏控制设置转向调整到最高了，还是没有解决问题
![圖片_2023-08-15_172412551](https://github.com/Yutong-gannis/ETSAuto/assets/95551416/96ad2929-994e-4c76-8f60-99029aaeb054)

**Comment by Lyric0620** [comment]
@see963852 目前2.0dev还有一些问题，未来几天会发布正式版本
