### ISSUE TITLE
Hello 我有一些問題 是否可以加個微信詢問

### ISSUE THREAD

**Issue by Mamgo1128** [Lyric0620/ETSAuto#62]

**Comment by Lyric0620** [comment]
@Mamgo1128 直接在这里问就行

**Comment by Mamgo1128** [comment]
@Yutong-gannis 請問有運行成功的截圖或影片嗎
因為不太確定是否正運行正確

**Comment by Lyric0620** [comment]
@Mamgo1128 没有的，你可以看ETSAuto.bat的五个程序是否都在运行，程序是否在控制车辆，用户界面是否显示车道线和目标框来进行确认。

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/8e76c0bb-8e38-45c9-8fa5-a7cfb39e10d7)
這樣是正常的嗎.....

**Comment by Lyric0620** [comment]
@Mamgo1128 一共五个程序，如果少了就关了重新打开

**Comment by Mamgo1128** [comment]
https://github.com/Yutong-gannis/ETSAuto/assets/124562166/687a5454-dbb3-4f44-8e24-95fad945aa43

痾....該怎麼辦

**Comment by Mamgo1128** [comment]
@Yutong-gannis 
requirements.txt 
裡的東西都確定裝好了

**Comment by Lyric0620** [comment]
@Mamgo1128 你是用的conda吗

**Comment by Mamgo1128** [comment]
是的

**Comment by Lyric0620** [comment]
@Mamgo1128 这样吧，你先开五个conda的命令行终端，分别运行.bat里的五个程序，看看报错

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/25c284eb-4f7f-49d1-9070-707fc18e272c)
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/8623787a-7757-4a9c-801d-1bbf94980623)
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/83e96814-4ede-4e79-85c9-8be0d81c3fc4)
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/f6f88454-d72d-4890-ab2f-300aa6f8f8b5)
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/630eca9f-250d-40a2-a015-63438a66bc70)

**Comment by Mamgo1128** [comment]
@Yutong-gannis 
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/02974180-3ff8-4236-8dfd-cb4b7486bf02)
是不是有少加這兩行阿

**Comment by Lyric0620** [comment]
@Mamgo1128 貌似没有添加项目路径，我改一下仓库，等会你再下载一遍

**Comment by Mamgo1128** [comment]
好的!

**Comment by Lyric0620** [comment]
@Mamgo1128 好了，你再试试

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/dc9221a2-af1f-4fa8-9c4c-41906d0f3cf7)
@Yutong-gannis 這邊這個嗎

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/184270fa-35f2-43e4-8110-0a28767f2169)
@Yutong-gannis 
報錯是正常的嗎

**Comment by Lyric0620** [comment]
@Mamgo1128 不正常，说明perception的数据没传过来，权重文件位置放对了吗

**Comment by Mamgo1128** [comment]
該放在哪裡呢

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/8dc5667a-0c9e-4471-ad72-8c44c5e16e61)
@Yutong-gannis 是這裡嗎
抱歉造成妳這麼多困擾

**Comment by Lyric0620** [comment]
@Mamgo1128 没问题的，那你看一下perception的log有什么

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/156fecda-5c7f-41dc-b878-4678f4dd4187)
好像沒有log

**Comment by Lyric0620** [comment]
@Mamgo1128 没关系的，程序里本来bug就多

**Comment by Mamgo1128** [comment]
@Yutong-gannis 
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/bb3a7f26-f765-439b-9943-5e9fa6bdfaa7)
請問一下我的weights應該沒有放錯位置吧

**Comment by Lyric0620** [comment]
@Mamgo1128 就是perception那个终端打印出来的，你也可以翻看外面log文件夹下的log文件中关于perception的信息

![2e65235560abedafa8264c3c1c511db](https://github.com/Yutong-gannis/ETSAuto/assets/69740611/a2635e2e-6497-48b5-86af-0cd4dd5a3e5a)

**Comment by Lyric0620** [comment]
@Mamgo1128 weight位置没问题

**Comment by Mamgo1128** [comment]
好像沒有好像沒有打印出perception的樣子

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/e93ab52d-4164-457f-8ee4-847b2c71ceed)

**Comment by Lyric0620** [comment]
@Mamgo1128 说明这个perception_launcher.py可能没有打开，你用终端打开试试

**Comment by Mamgo1128** [comment]
![image](https://github.com/Yutong-gannis/ETSAuto/assets/124562166/ba358d12-d424-4aeb-853e-67ae9fcd93be)

@Yutong-gannis

**Comment by Lyric0620** [comment]
@Mamgo1128 这个问题和cudnn安装有关，可能是环境变量什么的，你得上网搜一下

**Comment by Mamgo1128** [comment]
@Yutong-gannis 感想你 成功運行起來了!!!

**Comment by Lyric0620** [comment]
@Mamgo1128 没事没事
