### ISSUE TITLE
如何将2D框转到bev视角？

### ISSUE THREAD

**Issue by Fanfanyf** [Lyric0620/ETSAuto#63]
看到作者2D框转到bev视角后，框的尺寸似乎没有发生形变？好像相关代码里也没有对这块进行深度估计，想问是如何实现的

**Comment by Lyric0620** [comment]
@Fanfanyf 我只估计了二维平面位置，3D框长宽高是默认值

**Comment by Fanfanyf** [comment]
谢谢
